# Generated by Django 3.1.1 on 2020-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_swagger_tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='hash',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
