# Generated by Django 3.1.6 on 2021-02-13 22:11
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Names",
            fields=[
                ("custom_id_field", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
