# Generated by Django 3.1.6 on 2021-02-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="names",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[("mo", "Moses"), ("moi", "Moishe"), ("mu", "Mush")],
                default=None,
                max_length=254,
                null=True,
            ),
        ),
    ]
