name: Publish package

on:
  release:
    types: [published, edited]

jobs:
  build-and-publish-test:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/.github/workflows/publish@main
        with:
          overwrite-repository: true
          repository-url: https://test.pypi.org/legacy/
          token: ${{ secrets.TEST_PYPI_TOKEN }}
  build-and-publish:
    needs: build-and-publish-test
    runs-on: ubuntu-latest
    steps:
      - uses: snok/.github/workflows/publish@main
        with:
          token: ${{ secrets.PYPI_TOKEN }}
